global:
  timezone: Asia/Tokyo
  assets_path: /home/tokuhirom/project/unco/crawler/assets/
  log:
    # level: info
    level: debug

plugins:
  - module: Subscription::Config
    config:
      feed:
        - url: http://b.hatena.ne.jp/entrylist?mode=rss&sort=hot&threshold=5
        - url: http://b.hatena.ne.jp/hotentry?mode=rss
        - url: http://b.hatena.ne.jp/hotentry/news/rss
        - url: http://digg.com/technology/popular/24hours
        - url: http://api.pathtraq.com/newsite
        - url: http://api.pathtraq.com/popular?__lang=ja

  - module: Filter::Rule
    rule:
      module: Deduped

  - module: Filter::EntryFullText
    rule:
      expression: $args->{entry}->link !~ m{.*\.(jpg|pdf|swf|mov)$}
    config:
      store_html_on_failure: 1
      # はてブの詳細情報がでてきちゃうので。
      force_upgrade: 1

  # AutoPagerize でアップグレードしたる
  - module: Filter::EFTEX
    config:
      auto_pagerize_urls:
        - file:///home/tokuhirom/project/unco/autopagerize.json

  - module: Filter::ResolveRelativeLink

  - module: Filter::HatenaAnonDiary
  - module: Filter::HatenaDiaryKeywordUnlink
  - module: Filter::HatenaBookmarkUsersCount

  - module: Filter::HTMLScrubber
    config:
      rules:
        comment: 0
        style: 0
        script: 0

  - module: Publish::CHTML
    config:
      title: news aggregator
      work: /var/www/i/
      mobile_gw: http://mgw.hatena.ne.jp/?
      encoding: utf-8

  - module: Store::Unco
    config:
      connect_info: [ 'dbi:SQLite:/usr/local/webapp/unco/unco.db', ]

